name: Secure CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read   # ✅ least privilege

    env:
      API_KEY: ${{ secrets.API_KEY }}
      ADMIN_PASS: ${{ secrets.ADMIN_PASS }}

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Bandit (SAST)
      run: |
        pip install bandit
        bandit -r .

    - name: Run Safety (Dependency Scan)
      run: |
        pip install safety
        safety check

    - name: Run app
      run: python app.py
